# Base configs
# baseurl: "bongsokkang.github.io/photography"
images_fulls_loc: "/images/fulls"
images_thumbs_loc: "/images/fulls"
google_analytics: "UA-46465113-2"

# UI configs
title: "Landscaping throughout Southern Calfornia"
subtitle: "See the world through our eyes!"
author: "Ka Kyoung Landscaping"
header:
 title: "Ka Kyoung"
 subtitle: "Landscaping"
footer:
name: Ka Kyoung Landscaping
bio: Landscaping throughout Southern Calfornia
github: "Want a website like this for yourself for free? "
web_design: "Ka Kyoung Landscaping"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
